### PR TITLE
LogFormat for annotations and spans

### PR DESCRIPTION
**Pull request by khajavi**
This PR adds `annotations` which include all annotations in the `LogFormat`.
Also adds `span` and `spans` to include spans in the `LogFormat`.

### CODE REVIEW

**Comment by jdegoes** [comment]
@khajavi Good to merge when you fix conflicts!

**Review by jdegoes — DISMISSED** [review]

**Comment by khajavi** [comment]
@jdegoes 
Conflict resolved!

**Comment by khajavi** [comment]
@jdegoes 
Conflicts resolved!

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
🙏

**Pull request merged**
