### PR TITLE
Added Scala 2.11 to cross scala versions

### PR DESCRIPTION
**Pull request by andreyshikov**

### CODE REVIEW

**Comment by pshemass** [comment]
@mijicd could you look into that?

**Comment by andreyshikov** [comment]
> Please make sure to also include setting any compiler options, as well as the proper CircleCI steps. A good examples are [zio](https://github.com/zio/zio) and [zio-nio](https://github.com/zio/zio-nio).

thanks @mijicd 
I added 2.11 to circleci but silencer-lib dropped 2.11 support, so CI build fails.

**Comment by mijicd** [comment]
@andreyshikov That's fine, downgrading to `1.4.4` solves the problem (that's the version used in both repos I shared above).

**Comment by andreyshikov** [comment]
> @andreyshikov That's fine, downgrading it to `1.4.4` solves the problem (that's the version used in both repos I shared above).

ok, done

**Comment by mijicd** [comment]
Nice!

**Pull request merged**
