### PR TITLE
Handle positional arguments in slf4j bridge

### PR DESCRIPTION
**Pull request by virusdave**
See title.
Handles issue https://github.com/zio/zio-logging/issues/240

### CODE REVIEW

**Comment by pshemass** [comment]
@vigoo could you take a look on that ?

**Comment by vigoo** [comment]
Seems like `slf4j-api` has its own `MessageFormatter` that implements slf4j's logic and is faster than the standard string formatter (especially with the extra replace):
https://www.javadoc.io/doc/org.slf4j/slf4j-api/1.7.30/org/slf4j/helpers/MessageFormatter.html

I think we should use this one. @virusdave can you try it?

**Comment by virusdave** [comment]
> Seems like `slf4j-api` has its own `MessageFormatter` that implements slf4j's logic and is faster than the standard string formatter (especially with the extra replace):
> https://www.javadoc.io/doc/org.slf4j/slf4j-api/1.7.30/org/slf4j/helpers/MessageFormatter.html
> 
> I think we should use this one. @virusdave can you try it?

Moving this week, so not sure when I'll have time to get to it, but it looks simple enough to do (`s/String.format/MessageFormatter.format` in the original source).  If no one gets to it first, I'll do it, but it'll take me a couple days.

**Comment by pshemass** [comment]
@virusdave any update on that?

**Comment by aartigao** [comment]
This is a nice feature! ❤️ 

Any plan on fixing the conflicts and merging it @virusdave?

**Comment by jdegoes** [comment]
Will close for now, feel free to re-open against 2.0 work!

**Pull request closed without merging**
