### PR TITLE
Fix file loggers

### PR DESCRIPTION
**Pull request by guersam**
Use `LogWriter#writeln` to flush lines properly

### CODE REVIEW

**Comment by jdegoes** [comment]
@guersam Can you fix conflicts? Would love to get this merged in!

**Comment by guersam** [comment]
@jdegoes Sure, rebased it.

**Comment by justcoon** [comment]
@guersam can you sync your branch with master? thank you very much

**Comment by guersam** [comment]
Maybe I did something wrong with the git history... superseded by #466.

**Pull request closed without merging**
