### PR TITLE
Fixes trace level logging

### PR DESCRIPTION
**Pull request by gchudnov**
fixes https://github.com/zio/zio-logging/issues/454

At the moment it seems to be impossible to log on TRACE-level with slf4jLogger.
This PR intends to fix it.

Please review.

Thank you!

### CODE REVIEW

**Comment by jdegoes** [comment]
@gchudnov Thank you! Can you update with master, then I am happy to merge this?

**Comment by gchudnov** [comment]
hm. I messed up with the email a bit (used a corporate one initially) and edited it.

If it is messy and doesn't fit, can reopen the PR.

Thank you!

**Comment by gurghet** [comment]
This will be fine if squashed

**Comment by gchudnov** [comment]
@jdegoes 
it would be great to merge it and release in one of the future versions.

Thank you!

**Review by jdegoes — APPROVED** [review]

**Comment by jdegoes** [comment]
Thank you for your first contribution! 🙏

**Pull request merged**
